# Generated by Django 3.1.3 on 2020-11-10 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olymp',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Sex', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Height', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('Team', models.CharField(max_length=255)),
                ('NOC', models.CharField(max_length=50)),
                ('Games', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=50)),
                ('Season', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Sport', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('Medal', models.CharField(max_length=50)),
            ],
        ),
    ]
